FROM __TAG__

ARG PKG_NODE

ARG PKG_OS

ARG PKG_ARCH

ARG NPROC

RUN __DEPENDENCIES__

ENV PKG_CACHE_PATH=/fetched

RUN mkdir -p /fetched

RUN npx pkg-fetch -n ${PKG_NODE} -p ${PKG_OS} -a ${PKG_ARCH}

CMD ["sh"]