FROM __ARCH__/__TAG__

COPY bin/qemu-__QEMU__-static /usr/bin/

RUN apk update && apk --no-cache add git wget build-base python linux-headers

RUN npm install pkg-fetch && /node_modules/.bin/pkg-fetch __NODE_PKG__ __PKG_OS__ __PKG_ARCH__ \
    && mv ~/.pkg-cache/v*/fetched-* /

CMD ["/bin/bash"]