FROM arm32v6/node:alpine

COPY bin/qemu-arm-static /usr/bin/

RUN apk update && apk --no-cache add git wget build-base python paxctl linux-headers

ENV PKG_CACHE_PATH=/fetched

RUN mkdir -p /fetched && npm install pkg-fetch

RUN /node_modules/.bin/pkg-fetch node12 alpine armv6

CMD ["sh"]